/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mars.module.auvEditor;

import com.jme3.app.state.AppStateManager;
import com.jme3.renderer.ViewPort;
import com.jme3.system.awt.AwtPanel;
import com.jme3.system.awt.AwtPanelsContext;
import com.jme3.system.awt.PaintMode;
import java.awt.Dimension;
import java.util.Set;
import java.util.concurrent.Callable;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import mars.MARS_Main;
import mars.auv.AUV_Manager;
import mars.core.CentralLookup;
import org.openide.util.Lookup;

public final class LoadAUVVisualPanel1 extends JPanel {

    private Lookup.Result<MARS_Main> result = null;
    private AUV_Manager auv_manager = null;
    private static AwtPanel auvedpanel;

    /**
     * Creates new form LoadAUVVisualPanel1
     */
    public LoadAUVVisualPanel1() {
        initComponents();
        initAUV_Manager();
    }

    @Override
    public String getName() {
        return "Step #1";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LoadAUVVisualPanel1.class, "LoadAUVVisualPanel1.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void initAUV_Manager() {
        Lookup.Template template = new Lookup.Template(AUV_Manager.class);
        CentralLookup cl = CentralLookup.getDefault();
        result = cl.lookup(template);
        //result.addLookupListener(this);
        if (auv_manager == null) {// try to get mars, else its the listener
            auv_manager = cl.lookup(AUV_Manager.class);
            Set<String> auvNames = auv_manager.getAUVs().keySet();
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(auvNames.toArray()));
        }
    }

    public JComboBox getjComboBox1() {
        return jComboBox1;
    }
    
}
