/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mars.VegetationSystem;

import com.jme3.math.Vector2f;
import com.jme3.math.Vector3f;
import com.jme3.renderer.queue.RenderQueue;
import com.jme3.scene.Spatial;
import java.util.ArrayList;

final class VegetationSystemPanel extends javax.swing.JPanel {

    private final VegetationSystemOptionsPanelController controller;
    private ArrayList<VegetationSystem> vSList = new ArrayList<VegetationSystem>();
    private int selected = 0;
    private int channel = 0;
    private Vector2f wind = null;
    private RenderQueue.ShadowMode rShadow;
    private RenderQueue.ShadowMode gShadow;
    private RenderQueue.ShadowMode bShadow;
    private float randPR;
    private float randPG;
    private float randPB;
    private float randSR;
    private float randSG;
    private float randSB;
    private int jChooser = 0;
    
    VegetationSystemPanel(VegetationSystemOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plantWindow = new javax.swing.JDialog();
        texturePrev = new javax.swing.JPanel();
        texture = new javax.swing.JTextField();
        texPath = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        shadows = new javax.swing.JCheckBox();
        fade = new javax.swing.JCheckBox();
        thrustRes = new javax.swing.JCheckBox();
        windRes = new javax.swing.JCheckBox();
        plantApply = new javax.swing.JButton();
        texturePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        swayFreq = new javax.swing.JTextField();
        thrustRad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        scale = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        randPlant = new javax.swing.JSlider(0, 100);
        randSize = new javax.swing.JSlider(0, 100);
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        aDT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        settingsWindow = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        apply = new javax.swing.JButton();
        maxView = new javax.swing.JTextField();
        channelR = new javax.swing.JButton();
        channelG = new javax.swing.JButton();
        channelB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        windVec = new javax.swing.JTextField();
        chooser = new javax.swing.JDialog();
        jFileChooser = new javax.swing.JFileChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        systemList = new javax.swing.JList();
        createSystem = new javax.swing.JButton();
        dMapPath = new javax.swing.JTextField();
        patchSize = new javax.swing.JTextField();
        selectDMap = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        settings = new javax.swing.JButton();
        attach = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        texture.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.texture.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(texPath, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.texPath.text")); // NOI18N
        texPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texPathActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(shadows, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.shadows.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(fade, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.fade.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(thrustRes, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.thrustRes.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(windRes, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.windRes.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(plantApply, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.plantApply.text")); // NOI18N
        plantApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout texturePanelLayout = new javax.swing.GroupLayout(texturePanel);
        texturePanel.setLayout(texturePanelLayout);
        texturePanelLayout.setHorizontalGroup(
            texturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        texturePanelLayout.setVerticalGroup(
            texturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel3.text")); // NOI18N

        swayFreq.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.swayFreq.text")); // NOI18N

        thrustRad.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.thrustRad.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel7.text")); // NOI18N

        scale.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.scale.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel10.text")); // NOI18N

        aDT.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.aDT.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel11.text")); // NOI18N

        javax.swing.GroupLayout texturePrevLayout = new javax.swing.GroupLayout(texturePrev);
        texturePrev.setLayout(texturePrevLayout);
        texturePrevLayout.setHorizontalGroup(
            texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(texturePrevLayout.createSequentialGroup()
                .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantApply)
                    .addGroup(texturePrevLayout.createSequentialGroup()
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(texturePrevLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(texturePrevLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(randPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(texturePrevLayout.createSequentialGroup()
                                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(windRes)
                                            .addComponent(shadows)
                                            .addComponent(thrustRes)
                                            .addComponent(fade))
                                        .addGap(67, 67, 67))))
                            .addGroup(texturePrevLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(scale)
                                    .addComponent(texture, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texPath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(texturePrevLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(texturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(texturePrevLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(randSize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(texturePrevLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(texturePrevLayout.createSequentialGroup()
                                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(thrustRad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(swayFreq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        texturePrevLayout.setVerticalGroup(
            texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(texturePrevLayout.createSequentialGroup()
                .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(texturePrevLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texPath)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shadows)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fade)
                        .addGap(3, 3, 3)
                        .addComponent(thrustRes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(windRes))
                    .addGroup(texturePrevLayout.createSequentialGroup()
                        .addComponent(texturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(thrustRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(swayFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(texturePrevLayout.createSequentialGroup()
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(randSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(randPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(texturePrevLayout.createSequentialGroup()
                        .addGroup(texturePrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plantApply)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout plantWindowLayout = new javax.swing.GroupLayout(plantWindow.getContentPane());
        plantWindow.getContentPane().setLayout(plantWindowLayout);
        plantWindowLayout.setHorizontalGroup(
            plantWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texturePrev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        plantWindowLayout.setVerticalGroup(
            plantWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texturePrev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(apply, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.apply.text")); // NOI18N
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        maxView.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.maxView.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(channelR, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.channelR.text")); // NOI18N
        channelR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelRActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(channelG, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.channelG.text")); // NOI18N
        channelG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelGActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(channelB, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.channelB.text")); // NOI18N
        channelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelBActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel6.text")); // NOI18N

        windVec.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.windVec.text")); // NOI18N
        windVec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windVecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apply)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxView, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(windVec)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(channelG)
                            .addComponent(channelR, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(channelB, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(windVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(channelR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(channelG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(channelB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(apply)
                .addContainerGap())
        );

        javax.swing.GroupLayout settingsWindowLayout = new javax.swing.GroupLayout(settingsWindow.getContentPane());
        settingsWindow.getContentPane().setLayout(settingsWindowLayout);
        settingsWindowLayout.setHorizontalGroup(
            settingsWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        settingsWindowLayout.setVerticalGroup(
            settingsWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooserLayout = new javax.swing.GroupLayout(chooser.getContentPane());
        chooser.getContentPane().setLayout(chooserLayout);
        chooserLayout.setHorizontalGroup(
            chooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(chooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        chooserLayout.setVerticalGroup(
            chooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(chooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        systemList.setModel(new javax.swing.DefaultListModel()
        );
        systemList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                systemListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(systemList);

        org.openide.awt.Mnemonics.setLocalizedText(createSystem, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.createSystem.text")); // NOI18N
        createSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSystemActionPerformed(evt);
            }
        });

        dMapPath.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.dMapPath.text")); // NOI18N

        patchSize.setText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.patchSize.text")); // NOI18N
        patchSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patchSizeActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(selectDMap, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.selectDMap.text")); // NOI18N
        selectDMap.setToolTipText(org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.selectDMap.toolTipText")); // NOI18N
        selectDMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        settings.setVisible(false);
        org.openide.awt.Mnemonics.setLocalizedText(settings, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.settings.text")); // NOI18N
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        attach.setVisible(false);
        org.openide.awt.Mnemonics.setLocalizedText(attach, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.attach.text")); // NOI18N
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel14.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(VegetationSystemPanel.class, "VegetationSystemPanel.jLabel15.text")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(attach)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(createSystem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(settings))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dMapPath, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectDMap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patchSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dMapPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patchSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectDMap)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createSystem)
                            .addComponent(settings))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attach)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void windVecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windVecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_windVecActionPerformed

    private void patchSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patchSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patchSizeActionPerformed

    private void createSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSystemActionPerformed
        //vSList.add(new VegetationSystem(TERRAIN, ASSETMANAGER, CAMERA, new DensityMap(dMapPath.getText()), patchSize.getText()));
        javax.swing.DefaultListModel model = (javax.swing.DefaultListModel)systemList.getModel();
        model.addElement("VegSys" + vSList.size());
        settings.setVisible(true);
        attach.setVisible(true);
    }//GEN-LAST:event_createSystemActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        settingsWindow.setVisible(true);
    }//GEN-LAST:event_settingsActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed

        /*if(attach.getText().equals("Attach")){
            vSList.get(selected).attach(mars.core.CentralLookup.getDefault().lookup(Node.class)); //ToDo: Put MARS rootnode
            attach.setText("Detach");
        }else{
            vSList.get(selected).detach();
            attach.setText("Attach");
        }*/
    }//GEN-LAST:event_attachActionPerformed

    private void channelRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelRActionPerformed
        String[] windS = windVec.getText().split(",");
        wind = new Vector2f(Float.parseFloat(windS[0]), Float.parseFloat(windS[1]));
        
        String[] rangeS = maxView.getText().split(",");
        vSList.get(selected).setMaxView(Float.parseFloat(rangeS[0]), Float.parseFloat(rangeS[1]));
        
        channel = 0;        
        plantWindow.setVisible(true);
    }//GEN-LAST:event_channelRActionPerformed

    private void channelGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelGActionPerformed
        String[] windS = windVec.getText().split(",");
        wind = new Vector2f(Float.parseFloat(windS[0]),Float.parseFloat(windS[1]));
        
        String[] rangeS = maxView.getText().split(",");
        vSList.get(selected).setMaxView(Float.parseFloat(rangeS[0]), Float.parseFloat(rangeS[1]));
        
        channel = 1;
        plantWindow.setVisible(true);
    }//GEN-LAST:event_channelGActionPerformed

    private void channelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelBActionPerformed
        String[] windS = windVec.getText().split(",");
        wind = new Vector2f(Float.parseFloat(windS[0]),Float.parseFloat(windS[1]));
        
        String[] rangeS = maxView.getText().split(",");
        vSList.get(selected).setMaxView(Float.parseFloat(rangeS[0]), Float.parseFloat(rangeS[1]));
        
        channel = 2;
        plantWindow.setVisible(true);
    }//GEN-LAST:event_channelBActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        settingsWindow.setVisible(false);
        vSList.get(selected).setShadowModes(rShadow, rShadow, gShadow, gShadow, bShadow, bShadow);
        vSList.get(selected).plant(randPR, randPG, randPB, randSR, randSG, randSB);
    }//GEN-LAST:event_applyActionPerformed

    private void texPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texPathActionPerformed
        chooser.setVisible(true);
        jChooser = 1;
    }//GEN-LAST:event_texPathActionPerformed

    private void plantApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantApplyActionPerformed
        float sca1, sca2, sca3;
        String[] scaleS = scale.getText().split(",");
        if(scaleS.length < 3){
            sca1 = Float.parseFloat(scaleS[0]);
            sca2 = Float.parseFloat(scaleS[0]);
            sca3 = Float.parseFloat(scaleS[0]);
        }else{
            sca1 = Float.parseFloat(scaleS[0]);
            sca2 = Float.parseFloat(scaleS[1]);
            sca3 = Float.parseFloat(scaleS[2]);
        }
        
        Spatial gGrass = vSList.get(selected).createGenuineGrass(texture.getText(), Float.parseFloat(aDT.getText()), windRes.isSelected(), thrustRes.isSelected(), fade.isSelected(), wind, Float.parseFloat(swayFreq.getText()), Float.parseFloat(thrustRad.getText()), 2*Float.parseFloat(thrustRad.getText()), new Vector3f(sca1, sca2, sca3));
        Spatial iGrass = vSList.get(selected).createImposterGrass(texture.getText(), Float.parseFloat(aDT.getText()), windRes.isSelected(), thrustRes.isSelected(), fade.isSelected(), wind, Float.parseFloat(swayFreq.getText()), Float.parseFloat(thrustRad.getText()), 2*Float.parseFloat(thrustRad.getText()), new Vector3f(sca1, sca2, sca3));
        
        if(channel == 0){
            vSList.get(selected).setGenuineRed(gGrass);
            vSList.get(selected).setImposterRed(iGrass);
            if(shadows.isSelected()){
                rShadow = RenderQueue.ShadowMode.CastAndReceive;
            }else{
                rShadow = RenderQueue.ShadowMode.Off;
            }
            
            randPR = (float)(randPlant.getValue()/100);
            randSR = (float)(randSize.getValue()/100);
        }else if(channel == 1){
            vSList.get(selected).setGenuineGreen(gGrass);
            vSList.get(selected).setImposterGreen(iGrass);
            if(shadows.isSelected()){
                gShadow = RenderQueue.ShadowMode.CastAndReceive;
            }else{
                gShadow = RenderQueue.ShadowMode.Off;
            }
            
            randPG = (float)(randPlant.getValue()/100);
            randSG = (float)(randSize.getValue()/100);
        }else{
            vSList.get(selected).setGenuineBlue(gGrass);
            vSList.get(selected).setImposterBlue(iGrass);
            if(shadows.isSelected()){
                bShadow = RenderQueue.ShadowMode.CastAndReceive;
            }else{
                bShadow = RenderQueue.ShadowMode.Off;
            }
            
            randPB = (float)(randPlant.getValue()/100);
            randSB = (float)(randSize.getValue()/100);
        }
    }//GEN-LAST:event_plantApplyActionPerformed

    private void systemListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_systemListValueChanged
        selected = systemList.getSelectedIndex();
        /*if(MARSrootNode.getChildren().contains(vSList.get(selected)){
            attach.setText("Detach");
        }else{
            attach.setText("Attach");
        }*/
    }//GEN-LAST:event_systemListValueChanged

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        if(jChooser == 0){
            dMapPath.setText(jFileChooser.getSelectedFile().getAbsolutePath());
        }
        if(jChooser == 1){
            texture.setText(jFileChooser.getSelectedFile().getAbsolutePath());
        }
        chooser.setVisible(false);
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void selectDMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDMapActionPerformed
        chooser.setVisible(true);
        jChooser = 0;
    }//GEN-LAST:event_selectDMapActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(VegetationSystemPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(VegetationSystemPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(VegetationSystemPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(VegetationSystemPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aDT;
    private javax.swing.JButton apply;
    private javax.swing.JButton attach;
    private javax.swing.JButton channelB;
    private javax.swing.JButton channelG;
    private javax.swing.JButton channelR;
    private javax.swing.JDialog chooser;
    private javax.swing.JButton createSystem;
    private javax.swing.JTextField dMapPath;
    private javax.swing.JCheckBox fade;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maxView;
    private javax.swing.JTextField patchSize;
    private javax.swing.JButton plantApply;
    private javax.swing.JDialog plantWindow;
    private javax.swing.JSlider randPlant;
    private javax.swing.JSlider randSize;
    private javax.swing.JTextField scale;
    private javax.swing.JButton selectDMap;
    private javax.swing.JButton settings;
    private javax.swing.JDialog settingsWindow;
    private javax.swing.JCheckBox shadows;
    private javax.swing.JTextField swayFreq;
    private javax.swing.JList systemList;
    private javax.swing.JButton texPath;
    private javax.swing.JTextField texture;
    private javax.swing.JPanel texturePanel;
    private javax.swing.JPanel texturePrev;
    private javax.swing.JTextField thrustRad;
    private javax.swing.JCheckBox thrustRes;
    private javax.swing.JCheckBox windRes;
    private javax.swing.JTextField windVec;
    // End of variables declaration//GEN-END:variables
}
