/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mars.core;

import java.awt.EventQueue;
import mars.MARS_Main;

/**
 *
 * @author Thomas Tosik <tosik at iti.uni-luebeck.de>
 */
public class StartSimulationJPanel extends javax.swing.JPanel {

    MARS_Main mars = null;
    
    /**
     * Creates new form StartSimulationJPanel
     */
    public StartSimulationJPanel() {
        initComponents();
    }

    public void setMars(MARS_Main mars) {
        this.mars = mars;
    }
    
    public void allowSimInteraction(){
        EventQueue.invokeLater(new Runnable(){
                @Override
                public void run() {
                    jButtonPause.setEnabled(false);
                    jButtonPlay.setEnabled(true);
                    jButtonRestart.setEnabled(true);
                }
            }
        );
    }
    
   /**
     * 
     * @param allow
     */
    public void allowPhysicsInteraction(final boolean allow){
        EventQueue.invokeLater(new Runnable(){
                @Override
                public void run() {
                    jButtonPlay.setEnabled(!allow);
                    jButtonPause.setEnabled(allow);
                }
            }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonPlay = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        jButtonRestart = new javax.swing.JButton();

        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);

        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mars/gui/resources/icons/Play Green Button.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonPlay, org.openide.util.NbBundle.getMessage(StartSimulationJPanel.class, "StartSimulationJPanel.jButtonPlay.text")); // NOI18N
        jButtonPlay.setEnabled(false);
        jButtonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseClicked(evt);
            }
        });
        jToolBar1.add(jButtonPlay);

        jButtonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mars/gui/resources/icons/Pause Green Button.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonPause, org.openide.util.NbBundle.getMessage(StartSimulationJPanel.class, "StartSimulationJPanel.jButtonPause.text")); // NOI18N
        jButtonPause.setToolTipText(org.openide.util.NbBundle.getMessage(StartSimulationJPanel.class, "StartSimulationJPanel.jButtonPause.toolTipText")); // NOI18N
        jButtonPause.setEnabled(false);
        jButtonPause.setFocusable(false);
        jButtonPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPauseMouseClicked(evt);
            }
        });
        jToolBar1.add(jButtonPause);

        jButtonRestart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mars/gui/resources/icons/Backup Green Button.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonRestart, org.openide.util.NbBundle.getMessage(StartSimulationJPanel.class, "StartSimulationJPanel.jButtonRestart.text")); // NOI18N
        jButtonRestart.setToolTipText(org.openide.util.NbBundle.getMessage(StartSimulationJPanel.class, "StartSimulationJPanel.jButtonRestart.toolTipText")); // NOI18N
        jButtonRestart.setEnabled(false);
        jButtonRestart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRestartMouseClicked(evt);
            }
        });
        jToolBar1.add(jButtonRestart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayMouseClicked
        if(jButtonPlay.isEnabled()){
            if(mars != null){
                mars.startSimulation();
                jButtonPlay.setEnabled(false);
                jButtonPause.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonPlayMouseClicked

    private void jButtonPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPauseMouseClicked
       if(jButtonPause.isEnabled()){
            if(mars != null){
                mars.pauseSimulation();
                jButtonPause.setEnabled(false);
                jButtonPlay.setEnabled(true);
            } 
        }
    }//GEN-LAST:event_jButtonPauseMouseClicked

    private void jButtonRestartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRestartMouseClicked
        if(jButtonRestart.isEnabled()){
             if(mars != null){
                 mars.restartSimulation();
             }
        }
    }//GEN-LAST:event_jButtonRestartMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
