/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mars.water.options;

import mars.water.WaterState;
import mars.water.WaterHeightGenerator;

final class GridPanel extends javax.swing.JPanel {

    private final GridOptionsPanelController controller;
    private WaterState state;
    private WaterHeightGenerator gen;

    GridPanel(GridOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        while (WaterState.getInstance() == null);
        state = WaterState.getInstance();
        gen = state.getHeightGenerator();
        smallX.setText(String.valueOf(gen.getScalexsmall()));
        smallY.setText(String.valueOf(gen.getScaleysmall()));
        bigX.setText(String.valueOf(gen.getScalexbig()));
        bigY.setText(String.valueOf(gen.getScaleybig()));
        smallHeight.setText(String.valueOf(gen.getHeightsmall()));
        bigHeight.setText(String.valueOf(gen.getHeightbig()));
        smallSpeed.setText(String.valueOf(gen.getSpeedsmall()));
        bigSpeed.setText(String.valueOf(gen.getSpeedbig()));
        octaves.setText(String.valueOf(gen.getOctaves()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smallX = new javax.swing.JFormattedTextField();
        smallY = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        bigX = new javax.swing.JFormattedTextField();
        bigY = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        smallHeight = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        bigHeight = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        smallSpeed = new javax.swing.JFormattedTextField();
        bigSpeed = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        octaves = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        smallX.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.smallX.text")); // NOI18N
        smallX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallXActionPerformed(evt);
            }
        });

        smallY.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.smallY.text")); // NOI18N
        smallY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallYActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.jLabel1.text")); // NOI18N

        bigX.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.bigX.text")); // NOI18N
        bigX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigXActionPerformed(evt);
            }
        });

        bigY.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.bigY.text")); // NOI18N
        bigY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigYActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.jLabel2.text")); // NOI18N

        smallHeight.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.smallHeight.text")); // NOI18N
        smallHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallHeightActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.jLabel3.text")); // NOI18N

        bigHeight.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.bigHeight.text")); // NOI18N
        bigHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigHeightActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.jLabel4.text")); // NOI18N

        smallSpeed.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.smallSpeed.text")); // NOI18N
        smallSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallSpeedActionPerformed(evt);
            }
        });

        bigSpeed.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.bigSpeed.text")); // NOI18N
        bigSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigSpeedActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.jLabel6.text")); // NOI18N

        octaves.setText(org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.octaves.text")); // NOI18N
        octaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(GridPanel.class, "GridPanel.jLabel7.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(10, 10, 10))
                        .addComponent(jLabel2))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smallHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(octaves, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bigX)
                            .addComponent(smallX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bigY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(octaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void smallXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallXActionPerformed
        gen.setScalexsmall(Float.parseFloat(smallX.getText()));
    }//GEN-LAST:event_smallXActionPerformed

    private void smallYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallYActionPerformed
        gen.setScaleysmall(Float.parseFloat(smallY.getText()));
    }//GEN-LAST:event_smallYActionPerformed

    private void bigXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigXActionPerformed
        gen.setScalexbig(Float.parseFloat(bigX.getText()));
    }//GEN-LAST:event_bigXActionPerformed

    private void bigYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigYActionPerformed
        gen.setScaleybig(Float.parseFloat(bigY.getText()));
    }//GEN-LAST:event_bigYActionPerformed

    private void smallHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallHeightActionPerformed
        gen.setHeightsmall(Float.parseFloat(smallHeight.getText()));
    }//GEN-LAST:event_smallHeightActionPerformed

    private void bigHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigHeightActionPerformed
        gen.setHeightbig(Float.parseFloat(bigHeight.getText()));
    }//GEN-LAST:event_bigHeightActionPerformed

    private void smallSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallSpeedActionPerformed
        gen.setSpeedsmall(Float.parseFloat(smallSpeed.getText()));
    }//GEN-LAST:event_smallSpeedActionPerformed

    private void bigSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigSpeedActionPerformed
        gen.setSpeedbig(Float.parseFloat(bigSpeed.getText()));
    }//GEN-LAST:event_bigSpeedActionPerformed

    private void octavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavesActionPerformed
        gen.setOctaves(Integer.parseInt(octaves.getText()));
    }//GEN-LAST:event_octavesActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(GridPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(GridPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(GridPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(GridPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField bigHeight;
    private javax.swing.JFormattedTextField bigSpeed;
    private javax.swing.JFormattedTextField bigX;
    private javax.swing.JFormattedTextField bigY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField octaves;
    private javax.swing.JFormattedTextField smallHeight;
    private javax.swing.JFormattedTextField smallSpeed;
    private javax.swing.JFormattedTextField smallX;
    private javax.swing.JFormattedTextField smallY;
    // End of variables declaration//GEN-END:variables
}
