/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mars.water.options;

import mars.water.WaterGridFilter;
import mars.water.WaterState;
import org.openide.util.NbPreferences;

final class RefractionPanel extends javax.swing.JPanel {

    private final RefractionOptionsPanelController controller;
    private WaterState state;
    private WaterGridFilter filter;
    
    RefractionPanel(RefractionOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        while (WaterState.getInstance() == null);
        state = WaterState.getInstance();
        filter = state.getWaterFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enabled = new javax.swing.JCheckBox();
        strength = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        constant = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(enabled, org.openide.util.NbBundle.getMessage(RefractionPanel.class, "RefractionPanel.enabled.text")); // NOI18N
        enabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledActionPerformed(evt);
            }
        });

        strength.setText(org.openide.util.NbBundle.getMessage(RefractionPanel.class, "RefractionPanel.strength.text")); // NOI18N
        strength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(RefractionPanel.class, "RefractionPanel.jLabel1.text")); // NOI18N

        constant.setText(org.openide.util.NbBundle.getMessage(RefractionPanel.class, "RefractionPanel.constant.text")); // NOI18N
        constant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constantActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(RefractionPanel.class, "RefractionPanel.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enabled)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strength, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(constant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enabled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(constant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledActionPerformed
        filter.setUseRefraction(enabled.isSelected());
    }//GEN-LAST:event_enabledActionPerformed

    private void strengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthActionPerformed
        filter.setRefractionStrength(Float.parseFloat(strength.getText()));
    }//GEN-LAST:event_strengthActionPerformed

    private void constantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constantActionPerformed
        filter.setRefractionConstant(Float.parseFloat(constant.getText()));
    }//GEN-LAST:event_constantActionPerformed

    void load() {
        filter.setUseRefraction(NbPreferences.forModule(RefractionPanel.class).getBoolean("UseRefraction", true));
        filter.setRefractionStrength(NbPreferences.forModule(RefractionPanel.class).getFloat("RefractionStrength", .1f));
        filter.setRefractionConstant(NbPreferences.forModule(RefractionPanel.class).getFloat("RefractionConstant", .5f));
        
        enabled.setSelected(filter.isUseRefraction());
        strength.setText(String.valueOf(filter.getRefractionStrength()));
        constant.setText(String.valueOf(filter.getRefractionConstant()));
    }

    void store() {
        NbPreferences.forModule(RefractionPanel.class).putBoolean("UseRefraction", filter.isUseRefraction());
        NbPreferences.forModule(RefractionPanel.class).putFloat("RefractionStrength", filter.getRefractionStrength());
        NbPreferences.forModule(RefractionPanel.class).putFloat("RefractionConstant", filter.getRefractionConstant());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField constant;
    private javax.swing.JCheckBox enabled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField strength;
    // End of variables declaration//GEN-END:variables
}
